"""initial

Revision ID: 5a1a5ae14bd7
Revises: 
Create Date: 2026-03-21 18:40:00.881788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a1a5ae14bd7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('zip_code', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('google_maps_url', sa.String(length=512), nullable=True),
    sa.Column('facebook_url', sa.String(length=512), nullable=True),
    sa.Column('facebook_active', sa.Boolean(), nullable=False),
    sa.Column('facebook_last_post_date', sa.String(length=30), nullable=True),
    sa.Column('facebook_page_likes', sa.Integer(), nullable=True),
    sa.Column('instagram_handle', sa.String(length=100), nullable=True),
    sa.Column('instagram_active', sa.Boolean(), nullable=False),
    sa.Column('instagram_followers', sa.Integer(), nullable=True),
    sa.Column('instagram_last_post_date', sa.String(length=30), nullable=True),
    sa.Column('primary_social', sa.String(length=20), nullable=True),
    sa.Column('has_website', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('site_generated_at', sa.String(length=30), nullable=True),
    sa.Column('site_url', sa.String(length=255), nullable=True),
    sa.Column('email_sent_at', sa.String(length=30), nullable=True),
    sa.Column('email_opened_at', sa.String(length=30), nullable=True),
    sa.Column('sms_sent_at', sa.String(length=30), nullable=True),
    sa.Column('dm_sent_at', sa.String(length=30), nullable=True),
    sa.Column('replied_at', sa.String(length=30), nullable=True),
    sa.Column('converted_at', sa.String(length=30), nullable=True),
    sa.Column('deal_value', sa.Float(), nullable=True),
    sa.Column('monthly_recurring', sa.Float(), nullable=True),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_slug'), 'leads', ['slug'], unique=True)
    op.create_index(op.f('ix_leads_status'), 'leads', ['status'], unique=False)
    op.create_table('runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('started_at', sa.String(length=30), nullable=False),
    sa.Column('finished_at', sa.String(length=30), nullable=True),
    sa.Column('params', sa.Text(), nullable=False),
    sa.Column('stats', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outreach_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.String(length=30), nullable=False),
    sa.Column('delivered', sa.Boolean(), nullable=True),
    sa.Column('opened', sa.Boolean(), nullable=True),
    sa.Column('opened_at', sa.String(length=30), nullable=True),
    sa.Column('replied', sa.Boolean(), nullable=True),
    sa.Column('replied_at', sa.String(length=30), nullable=True),
    sa.Column('bounced', sa.Boolean(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lead_id', 'channel', 'sequence_number', name='uq_outreach_lead_channel_seq')
    )
    op.create_index('idx_outreach_lead_channel', 'outreach_log', ['lead_id', 'channel'], unique=False)
    op.create_table('scraped_content',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('image_path', sa.String(length=512), nullable=True),
    sa.Column('image_category', sa.String(length=50), nullable=True),
    sa.Column('scraped_at', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('site_analytics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=True),
    sa.Column('page_views', sa.Integer(), nullable=False),
    sa.Column('unique_visitors', sa.Integer(), nullable=False),
    sa.Column('cta_clicks', sa.Integer(), nullable=False),
    sa.Column('last_viewed_at', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suppressions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('reason', sa.String(length=30), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_suppressions_email', 'suppressions', ['email'], unique=False)
    op.create_index('idx_suppressions_lead', 'suppressions', ['lead_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_suppressions_lead', table_name='suppressions')
    op.drop_index('idx_suppressions_email', table_name='suppressions')
    op.drop_table('suppressions')
    op.drop_table('site_analytics')
    op.drop_table('scraped_content')
    op.drop_index('idx_outreach_lead_channel', table_name='outreach_log')
    op.drop_table('outreach_log')
    op.drop_table('runs')
    op.drop_index(op.f('ix_leads_status'), table_name='leads')
    op.drop_index(op.f('ix_leads_slug'), table_name='leads')
    op.drop_table('leads')
    # ### end Alembic commands ###
